[workspace]
members = ["crates/base", "crates/cli", "crates/recipe"]
resolver = "2"

[workspace.dependencies]

anstream = "1.0.0"
ecow = "0.2.6"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
parking_lot = "0.12.5"
serde = "1.0.228"
kdl = "6.5.0"
xflags = "0.3.2"

expect-test = "1.5.1"
