[package]
name = "nao-recipe"
version = "0.1.7"
edition = "2024"
description = "Recipe definitions for the nao task runner"
license = "MIT"
repository = "https://github.com/manuel-woelker/nao"

[lib]
path = "src/lib.rs"

[dependencies]
kdl = { workspace = true }
miette = { version = "7.6.0", features = ["fancy"] }
nao-base = { path = "../base", version = "0.1.7" }
nao-pal = { path = "../pal", version = "0.1.7" }

[dev-dependencies]
expect-test = { workspace = true }
