[package]
name = "nao-engine"
version = "0.1.2"
edition = "2024"
description = "Run planning engine for the nao task runner"
license = "MIT"
repository = "https://github.com/manuel-woelker/nao"

[lib]
path = "src/lib.rs"

[dependencies]
nao-base = { path = "../base", version = "0.1.2" }
nao-pal = { path = "../pal", version = "0.1.2" }
nao-recipe = { path = "../recipe", version = "0.1.2" }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting"] }

[dev-dependencies]
expect-test = { workspace = true }
