[package]
name = "nao-pal"
version = "0.1.6"
edition = "2024"
description = "Platform abstraction layer for the nao task runner"
license = "MIT"
repository = "https://github.com/manuel-woelker/nao"

[dependencies]
nao-base = { path = "../base", version = "0.1.6" }
expect-test = {workspace = true}
filetime = {workspace = true}
ignore = {workspace = true}
libc = {workspace = true}
notify-debouncer-full = {workspace = true}
relative-path = {workspace = true}
tokio = { version = "1.44.2", features = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }
